name: fancy_weather
description: Simple weather app

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 2.0.0

environment:
  sdk: ">=2.11.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4
  http: ^0.13.4
  geolocator: ^8.0.1
  flutter_spinkit: ^5.1.0
  syncfusion_flutter_charts: ^19.4.38
  syncfusion_flutter_gauges: ^19.4.38
  cached_network_image: ^3.2.0
  intl: ^0.17.0
  pull_to_refresh: ^2.0.0
  redux: ^5.0.0
  flutter_redux: ^0.8.2
  flutter_jailbreak_detection: ^1.8.0
  connectivity: ^3.0.6
  shared_preferences: ^2.0.11
  # flutter_weather_bg: ^2.8.2
  
  # provider: ^6.0.1
  # shared_preferences: ^2.0.11
  # awesome_dialog: ^2.1.2

dev_dependencies:

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Italic.ttf
          style: italic
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700